# Generated by Django 5.1.7 on 2025-03-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
